// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGuxvcJw67so4ApEggopFMxU0gjSPizIQ',
    appId: '1:1070624676579:web:59edd6440c9e8c764043d6',
    messagingSenderId: '1070624676579',
    projectId: 'kostgo-9e183',
    authDomain: 'kostgo-9e183.firebaseapp.com',
    storageBucket: 'kostgo-9e183.firebasestorage.app',
    measurementId: 'G-8905M5HXX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6VpMVR521dO2gk9cdP1M6BHR8VJgSCSo',
    appId: '1:1070624676579:android:ad7705a2fe24547f4043d6',
    messagingSenderId: '1070624676579',
    projectId: 'kostgo-9e183',
    storageBucket: 'kostgo-9e183.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCubAViJIEf5AZTHA-Hjr-LnwhB7Bypuw8',
    appId: '1:1070624676579:ios:43a3ba351358615c4043d6',
    messagingSenderId: '1070624676579',
    projectId: 'kostgo-9e183',
    storageBucket: 'kostgo-9e183.firebasestorage.app',
    iosBundleId: 'com.example.kostgo',
  );

}